# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9995a2c91b1e2d45f9b5a6c15147952175f492421ef47151a42a2ba9a99cfea38b9f1bafc2f408939f35307d7d3b4062d673c14acc8a5dccf8eab218cf5d5b0

test:
  secret_key_base: 5c500ffd35a0d12223eef75b424cdd5333b13b47ef64efd9398136a712a07f0c9e273c38ca7d9fa890103fd3199f58160e1f1ca6bc887dda5862935fe1adbe20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
